---
testing:
  watch: /merlin/testing
  templates:
    "config/examples/templates/testing.conf.erb": testing.conf
  destination: /tmp/testing/
  atomic: true
  statics:
    config/examples/static/test.txt: test.txt
  check_cmd: echo "This is the check command <%= dest %>"
  commit_cmd: echo "This is the commit command <%= dest %>"

